### ISSUE TITLE
Pb versions de dépendances avec l'install des dev requirements de GeoNature

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/Habref-api-module#4]
L'installaion des dépendances de dev de GeoNature Backend provoquent une erreur lié à la version de click.

Black 20.8b0 requiert click >= 7.1.2
Habref-api-module requiert strictement click == 6.7.

Cela provoque une erreur (cf. ci-après).

Ne pourrais-t-on pas envisager d’utiliser des outils aujourd'hui plus avancés pour gérer les projets Python. Je pense notamment à [poetry](https://python-poetry.org/) qui est simple, fonctionne très bien et gère bien mieux les versions de dépendances. L'équivalent NPM pour Python.

J'ai commencé à l'utiliser sur [GN2PG](https://github.com/lpoaura/GN2PG) et commence à le généraliser sur tous mes projets Python.

**Comment by lpofredc** [comment]
l'erreur sur un `python -m pip install -r requirements-dev.txt`

```
...
Building wheels for collected packages: black
  Building wheel for black (PEP 517) ... done
  Created wheel for black: filename=black-20.8b1-py3-none-any.whl size=124184 sha256=faa6890c4775cb4f907b38c80cab662fa78a5b76ef2099fa4fd2804b06d0a608
  Stored in directory: /home/geonature/.cache/pip/wheels/c5/85/79/f3af8daaf8037c0bf14beb3b7a1511a39b6e6902ca2aaf494e
Successfully built black
Installing collected packages: typed-ast, regex, pathspec, mypy-extensions, click, appdirs, black
  Attempting uninstall: click
    Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pypn-habref-api 0.1.4 requires click==6.7, but you have click 7.1.2 which is incompatible.
...
```

**Comment by lpofredc** [comment]
Se pose aussi la question, sur ce package de la dépendance à `click` qui ne semble être utilisé que pour un `click.echo` 😄

**Comment by bouttier** [comment]
Oui ce problème se pose souvent en raison d’un pinning de version dans le setup.py des différents modules. Or ce n’est pas le rôle du setup.py de décrire l’environnement de déploiement souhaité. J’ai commencé pour certains modules, notamment sur la branche alembic car j’avais besoin d’un packaging des modules, à supprimer ce pinning (ou à minima à indiquer les versions avec des >=). Exemple pour Habref :
- Chargements des requirements depuis `requirements.in` : https://github.com/PnX-SI/Habref-api-module/blob/alembic/setup.py#L10
- `requirements.in` sans pinning : https://github.com/PnX-SI/Habref-api-module/blob/alembic/requirements.in

Au delà de ce problème, on gagnerait certainement à passer à poetry :-)

**Comment by TheoLechemia** [comment]
On a mis des versions de dépendances plus souple pour la prochaine release (voir branche develop: on ne fixe plus la version exacte des dépendances).
Et oui c'est plus peu de l'excès de zèle le "click" pour ce module, mais c'est une dépendance de Flask, donc tant qu'à faire !
